export default {
  ACTION: 'ACTION',
  SELECTED: 'SELECTED',
  MULTI_LINE: 'MULTI_LINE',
  TOGGLE_ACTION: 'TOGGLE_ACTION',
  CHECKBOX_ACTION: 'CHECKBOX_ACTION',
  STATUS: 'STATUS',
  INPUT: 'INPUT',
  UPDATED_AT: 'UPDATED_AT',
}
