// Barrel re-export so existing `import { X } from '~/constants/mockData'` call sites
// across the codebase don't need to change — the domain split lives entirely in here.
export * from './admin'
export * from './auth'
export * from './companies'
export * from './contracts'
export * from './tags'
export * from './leads'
export * from './prospects'
export * from './deals'
export * from './team'
export * from './payments'
export * from './products'
export * from './projects'
export * from './quotes'
export * from './tasks'
